// Atlas del Arte — datos del blog de MANCHA (bilingüe ES/EN).
// Las imágenes usan Wikimedia Special:FilePath (URL canónica estable).
// Solo se enlazan obras/retratos de dominio público.

export function wiki(filename, width = 700) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(filename)}?width=${width}`;
}

// Devuelve todo el atlas localizado. L(es, en) elige según el idioma.
export function getAtlas(locale) {
  const L = (es, en) => (locale === 'en' ? en : es);

  const datosTicker = [
    L('El arte rupestre más antiguo conocido tiene 45.500 años — un cerdo pintado en Sulawesi.', 'The oldest known cave art is 45,500 years old — a pig painted in Sulawesi.'),
    L('Van Gogh vendió apenas 1 a 4 cuadros en vida. Hoy domina el top de subastas.', 'Van Gogh sold just 1 to 4 paintings in his lifetime. Today he tops the auction charts.'),
    L('El azul ultramarino llegó a valer más que el oro por gramo.', 'Ultramarine blue was once worth more than gold by weight.'),
    L('La Mona Lisa no tiene cejas.', 'The Mona Lisa has no eyebrows.'),
    L('El arte fue disciplina olímpica con medallas entre 1912 y 1948.', 'Art was an Olympic discipline with medals between 1912 and 1948.'),
    L('Picasso creó cerca de 50.000 obras a lo largo de su vida.', 'Picasso created around 50,000 works over his lifetime.'),
    L('El "Salvator Mundi" se vendió por 450 millones y nadie sabe dónde está hoy.', 'The "Salvator Mundi" sold for 450 million and no one knows where it is today.'),
    L('Yves Klein patentó su propio tono de azul: el IKB.', 'Yves Klein patented his own shade of blue: IKB.'),
    L('Banksy trituró su obra en plena subasta de Sotheby\'s en 2018.', 'Banksy shredded his own work mid-auction at Sotheby\'s in 2018.'),
  ];

  const datosCuriosos = [
    { color: 'var(--red)', dato: L('Recorrer el Louvre dedicando 30 segundos a cada obra te tomaría cerca de 100 días sin dormir.', 'Touring the Louvre at 30 seconds per work would take about 100 days without sleep.') },
    { color: 'var(--lilac-deep)', dato: L('Leonardo da Vinci escribía al revés, en escritura especular: solo legible frente a un espejo.', 'Leonardo da Vinci wrote backwards, in mirror script: only legible in a mirror.') },
    { color: 'var(--yellow-deep)', dato: L('El "mummy brown", pigmento popular del siglo XVIII, se fabricaba con momias egipcias molidas.', '"Mummy brown", a popular 18th-century pigment, was made from ground Egyptian mummies.') },
    { color: 'var(--ink)', dato: L('Hokusai pintó "La gran ola" pasados los 70 años, y firmaba como "el viejo loco por el dibujo".', 'Hokusai painted "The Great Wave" past age 70, signing as "the old man mad about drawing".') },
    { color: 'var(--red-deep)', dato: L('El "Cuadrado negro" de Malévich tiene grietas que revelan colores ocultos bajo la pintura.', 'Malevich\'s "Black Square" has cracks revealing hidden colors beneath the paint.') },
    { color: 'var(--violet-deep)', dato: L('Rembrandt firmaba solo con su nombre de pila, como los maestros italianos que admiraba.', 'Rembrandt signed only with his first name, like the Italian masters he admired.') },
  ];

  const artistas = [
    { n: 1, nombre: 'Leonardo da Vinci', anos: '1452–1519', mov: L('Alto Renacimiento', 'High Renaissance'), pais: L('Italia', 'Italy'), color: 'var(--yellow-deep)', obra: L('La Gioconda', 'Mona Lisa'), img: wiki('Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg'), desc: L('El arquetipo del genio universal. Fundió ciencia y pintura como nadie; su sfumato disolvió el contorno y enseñó a pintar el aire entre las cosas.', 'The archetype of the universal genius. He fused science and painting like no one else; his sfumato dissolved the outline and taught us to paint the air between things.') },
    { n: 2, nombre: 'Miguel Ángel', anos: '1475–1564', mov: L('Alto Renacimiento', 'High Renaissance'), pais: L('Italia', 'Italy'), color: 'var(--ink)', obra: L('La creación de Adán', 'The Creation of Adam'), img: wiki('Michelangelo - Creation of Adam (cropped).jpg'), desc: L('Escultor antes que pintor, talló cuerpos que parecen respirar. La Capilla Sixtina la pintó de pie durante cuatro años, no acostado.', 'A sculptor before a painter, he carved bodies that seem to breathe. He painted the Sistine Chapel standing for four years, not lying down.') },
    { n: 3, nombre: 'Caravaggio', anos: '1571–1610', mov: L('Barroco', 'Baroque'), pais: L('Italia', 'Italy'), color: 'var(--ink)', obra: L('La vocación de San Mateo', 'The Calling of Saint Matthew'), img: wiki('The Calling of Saint Matthew-Caravaggo (1599-1600).jpg'), desc: L('Inventó el claroscuro dramático: luz cruda sobre fondo negro. Pintó santos con cara de gente de la calle y cambió el rumbo del Barroco.', 'He invented dramatic chiaroscuro: raw light over black. He painted saints with the faces of ordinary people and changed the course of the Baroque.') },
    { n: 4, nombre: 'Rembrandt', anos: '1606–1669', mov: L('Barroco neerlandés', 'Dutch Baroque'), pais: L('Países Bajos', 'Netherlands'), color: 'var(--red-deep)', obra: L('La ronda de noche', 'The Night Watch'), img: wiki('The Night Watch - HD.jpg'), desc: L('El mayor retratista de la intimidad humana. Sus autorretratos son una autobiografía pintada: del joven seguro al viejo arruinado y sabio.', 'The greatest portraitist of human intimacy. His self-portraits are a painted autobiography: from the confident youth to the ruined, wise old man.') },
    { n: 5, nombre: 'Diego Velázquez', anos: '1599–1660', mov: L('Barroco español', 'Spanish Baroque'), pais: L('España', 'Spain'), color: 'var(--ink)', obra: L('Las Meninas', 'Las Meninas'), img: wiki('Las Meninas, by Diego Velázquez, from Prado in Google Earth.jpg'), desc: L('"Las Meninas" es quizá el cuadro más analizado de la historia: un juego de espejos y miradas que mete al espectador dentro de la escena.', '"Las Meninas" may be the most analyzed painting in history: a play of mirrors and gazes that pulls the viewer into the scene.') },
    { n: 6, nombre: 'Johannes Vermeer', anos: '1632–1675', mov: L('Barroco neerlandés', 'Dutch Baroque'), pais: L('Países Bajos', 'Netherlands'), color: 'var(--lilac-deep)', obra: L('La joven de la perla', 'Girl with a Pearl Earring'), img: wiki('1665 Girl with a Pearl Earring.jpg'), desc: L('Pintó apenas unas 35 obras conocidas, todas de una quietud luminosa. Maestro absoluto de la luz que entra por una ventana.', 'He painted barely 35 known works, all of a luminous stillness. The absolute master of light coming through a window.') },
    { n: 7, nombre: 'Francisco de Goya', anos: '1746–1828', mov: L('Romanticismo', 'Romanticism'), pais: L('España', 'Spain'), color: 'var(--ink)', obra: L('El 3 de mayo de 1808', 'The Third of May 1808'), img: wiki('El Tres de Mayo, by Francisco de Goya, from Prado thin black margin.jpg'), desc: L('El puente entre lo antiguo y lo moderno. Sus "Pinturas negras", hechas con plomo en las paredes de su casa, anticiparon el siglo XX entero.', 'The bridge between the old and the modern. His "Black Paintings", made in lead on the walls of his house, anticipated the entire 20th century.') },
    { n: 8, nombre: 'Claude Monet', anos: '1840–1926', mov: L('Impresionismo', 'Impressionism'), pais: L('Francia', 'France'), color: 'var(--lilac)', obra: L('Impresión, sol naciente', 'Impression, Sunrise'), img: wiki('Claude Monet, Impression, soleil levant.jpg'), desc: L('Su cuadro le dio nombre a todo un movimiento. Pasó sus últimos años pintando los mismos nenúfares una y otra vez, persiguiendo la luz.', 'His painting gave a whole movement its name. He spent his final years painting the same water lilies over and over, chasing the light.') },
    { n: 9, nombre: 'Vincent van Gogh', anos: '1853–1890', mov: L('Postimpresionismo', 'Post-Impressionism'), pais: L('Países Bajos', 'Netherlands'), color: 'var(--yellow)', obra: L('La noche estrellada', 'The Starry Night'), img: wiki('Van Gogh - Starry Night - Google Art Project.jpg'), desc: L('El símbolo del artista incomprendido. Pintó más de 2.000 obras en una década, casi sin vender nada. Hoy es leyenda mundial.', 'The symbol of the misunderstood artist. He painted over 2,000 works in a decade, selling almost nothing. Today he is a global legend.') },
    { n: 10, nombre: 'Paul Cézanne', anos: '1839–1906', mov: L('Postimpresionismo', 'Post-Impressionism'), pais: L('Francia', 'France'), color: 'var(--yellow-deep)', obra: L('Monte Sainte-Victoire', 'Mont Sainte-Victoire'), img: wiki('Paul Cézanne 110.jpg'), desc: L('"El padre de todos nosotros", lo llamaron Picasso y Matisse. Descompuso la naturaleza en planos y abrió la puerta al cubismo.', '"The father of us all", Picasso and Matisse called him. He broke nature down into planes and opened the door to Cubism.') },
    { n: 11, nombre: 'Gustav Klimt', anos: '1862–1918', mov: L('Modernismo / Secesión', 'Modernism / Secession'), pais: L('Austria', 'Austria'), color: 'var(--yellow)', obra: L('El beso', 'The Kiss'), img: wiki('The Kiss - Gustav Klimt - Google Cultural Institute.jpg'), desc: L('Oro, patrones y erotismo. Su "período dorado" produjo íconos absolutos. En 2025 un Klimt batió el récord de arte moderno en subasta.', 'Gold, patterns and eroticism. His "golden period" produced absolute icons. In 2025 a Klimt broke the modern-art auction record.') },
    { n: 12, nombre: 'Pablo Picasso', anos: '1881–1973', mov: L('Cubismo', 'Cubism'), pais: L('España', 'Spain'), color: 'var(--red)', obra: L('Guernica', 'Guernica'), img: wiki('Guernica.jpg'), desc: L('Reinventó la pintura más de una vez. Cofundó el cubismo y, con "Guernica", hizo del arte un grito político imposible de ignorar.', 'He reinvented painting more than once. He co-founded Cubism and, with "Guernica", made art a political cry impossible to ignore.') },
    { n: 13, nombre: 'Henri Matisse', anos: '1869–1954', mov: L('Fauvismo', 'Fauvism'), pais: L('Francia', 'France'), color: 'var(--red)', obra: L('La danza', 'The Dance'), img: wiki('Grande_odalisque_à_la_culotte_bayadère_-_Henri_Matisse.jpg'), desc: L('El maestro del color puro y la línea libre. En la vejez, sin poder pintar, inventó los recortes de papel: arte con tijeras.', 'The master of pure color and the free line. In old age, unable to paint, he invented the paper cut-outs: art with scissors.') },
    { n: 14, nombre: 'Marcel Duchamp', anos: '1887–1968', mov: L('Dadaísmo', 'Dada'), pais: L('Francia', 'France'), color: 'var(--ink)', obra: L('La fuente', 'Fountain'), img: wiki('Duchamp Fountaine.jpg'), desc: L('Puso un urinario en una galería y firmó "R. Mutt". Con ese gesto preguntó qué es el arte — y el arte conceptual no volvió a ser igual.', 'He put a urinal in a gallery and signed it "R. Mutt". With that gesture he asked what art is — and conceptual art was never the same.') },
    { n: 15, nombre: 'Frida Kahlo', anos: '1907–1954', mov: L('Surrealismo / Folk', 'Surrealism / Folk'), pais: L('México', 'Mexico'), color: 'var(--lilac)', obra: L('Las dos Fridas', 'The Two Fridas'), img: wiki('Frida Kahlo, by Guillermo Kahlo.jpg'), desc: L('Convirtió el dolor físico y emocional en un lenguaje visual propio. Sus autorretratos son hoy un emblema global de identidad y resistencia.', 'She turned physical and emotional pain into a visual language of her own. Her self-portraits are now a global emblem of identity and resistance.') },
    { n: 16, nombre: 'Salvador Dalí', anos: '1904–1989', mov: L('Surrealismo', 'Surrealism'), pais: L('España', 'Spain'), color: 'var(--lilac-deep)', obra: L('La persistencia de la memoria', 'The Persistence of Memory'), img: wiki('Salvador Dali NYWTS.jpg'), desc: L('El showman del subconsciente. Sus relojes blandos volvieron cotidiano lo onírico, y él mismo se convirtió en obra de arte y personaje.', 'The showman of the subconscious. His soft clocks made the dreamlike everyday, and he turned himself into both artwork and character.') },
    { n: 17, nombre: 'Georgia O\'Keeffe', anos: '1887–1986', mov: L('Modernismo americano', 'American Modernism'), pais: L('EE. UU.', 'USA'), color: 'var(--red-deep)', obra: L('Flores y desiertos', 'Flowers and deserts'), img: wiki('Alfred Stieglitz - Georgia O\'Keeffe - Google Art Project.jpg'), desc: L('La madre del modernismo estadounidense. Sus flores monumentales y los paisajes de Nuevo México redefinieron la mirada sobre la naturaleza.', 'The mother of American modernism. Her monumental flowers and New Mexico landscapes redefined how we look at nature.') },
    { n: 18, nombre: 'Jackson Pollock', anos: '1912–1956', mov: L('Expresionismo abstracto', 'Abstract Expressionism'), pais: L('EE. UU.', 'USA'), color: 'var(--ink)', obra: L('Number 1A', 'Number 1A'), img: wiki('Jackson Pollock.jpg'), desc: L('El "dripping": pintar goteando sobre el lienzo en el suelo, con todo el cuerpo. Liberó a la pintura del caballete y del control.', 'The "drip": painting by dripping onto canvas on the floor, with the whole body. He freed painting from the easel and from control.') },
    { n: 19, nombre: 'Andy Warhol', anos: '1928–1987', mov: L('Pop Art', 'Pop Art'), pais: L('EE. UU.', 'USA'), color: 'var(--lilac)', obra: L('Latas de sopa Campbell', 'Campbell\'s Soup Cans'), img: wiki('Andy Warhol 1975.jpg'), desc: L('Borró la frontera entre arte y consumo. Sopas, billetes y celebridades repetidas en serie: el espejo perfecto del siglo del marketing.', 'He erased the line between art and consumption. Soups, banknotes and celebrities repeated in series: the perfect mirror of the marketing century.') },
    { n: 20, nombre: 'Jean-Michel Basquiat', anos: '1960–1988', mov: L('Neoexpresionismo', 'Neo-Expressionism'), pais: L('EE. UU.', 'USA'), color: 'var(--red)', obra: L('Untitled (1982)', 'Untitled (1982)'), img: wiki('Jean-Michel Basquiat.jpg'), desc: L('Pasó del grafiti en el Lower East Side a romper récords de subasta. Murió a los 27. Primer artista negro en alcanzar el centro del mercado.', 'He went from graffiti in the Lower East Side to breaking auction records. He died at 27. The first Black artist to reach the center of the market.') },
  ];

  const cuadrosCaros = [
    { pos: 1, obra: 'Salvator Mundi', autor: L('Leonardo da Vinci (atribuido)', 'Leonardo da Vinci (attributed)'), ano: L('1500 ca.', 'c. 1500'), precio: '450,3', donde: 'Christie\'s · 2017', nota: L('El cuadro más caro jamás vendido. Su comprador y su paradero actual son un misterio.', 'The most expensive painting ever sold. Its buyer and current whereabouts are a mystery.') },
    { pos: 2, obra: 'Interchange', autor: 'Willem de Kooning', ano: '1955', precio: '300', donde: L('Venta privada · 2015', 'Private sale · 2015'), nota: L('Una de las ventas privadas más altas de la historia del expresionismo abstracto.', 'One of the highest private sales in the history of abstract expressionism.') },
    { pos: 3, obra: L('Los jugadores de cartas', 'The Card Players'), autor: 'Paul Cézanne', ano: '1893', precio: '250', donde: L('Venta privada · 2011', 'Private sale · 2011'), nota: L('Comprado por la familia real de Catar. Una de cinco versiones del mismo motivo.', 'Bought by the royal family of Qatar. One of five versions of the same motif.') },
    { pos: 4, obra: L('Retrato de Elisabeth Lederer', 'Portrait of Elisabeth Lederer'), autor: 'Gustav Klimt', ano: '1916', precio: '236,4', donde: 'Sotheby\'s · 2025', nota: L('Récord absoluto para arte moderno en subasta. La obra fue confiscada por los nazis en 1938.', 'Absolute record for modern art at auction. The work was confiscated by the Nazis in 1938.') },
    { pos: 5, obra: L('Nafea faa ipoipo (¿Cuándo te casas?)', 'Nafea faa ipoipo (When Will You Marry?)'), autor: 'Paul Gauguin', ano: '1892', precio: '210', donde: L('Venta privada · 2014', 'Private sale · 2014'), nota: L('Pintado en Tahití, durante el período más célebre del artista.', 'Painted in Tahiti, during the artist\'s most celebrated period.') },
    { pos: 6, obra: 'Number 17A', autor: 'Jackson Pollock', ano: '1948', precio: '200', donde: L('Venta privada · 2015', 'Private sale · 2015'), nota: L('Dripping puro de la época dorada del expresionismo abstracto.', 'Pure drip from the golden age of abstract expressionism.') },
    { pos: 7, obra: L('Les femmes d\'Alger (Versión O)', 'Les femmes d\'Alger (Version O)'), autor: 'Pablo Picasso', ano: '1955', precio: '179,4', donde: 'Christie\'s · 2015', nota: L('Homenaje de Picasso a Delacroix; récord para el artista en su momento.', 'Picasso\'s homage to Delacroix; a record for the artist at the time.') },
    { pos: 8, obra: 'Nu couché', autor: 'Amedeo Modigliani', ano: '1917', precio: '170,4', donde: 'Christie\'s · 2015', nota: L('Sus desnudos escandalizaron en 1917; hoy son de lo más cotizado del mercado.', 'His nudes scandalized in 1917; today they are among the most sought-after on the market.') },
  ];

  const museos = [
    { nombre: L('Museo del Louvre', 'The Louvre'), ciudad: L('París, Francia', 'Paris, France'), color: 'var(--red)', joya: L('La Gioconda · La Victoria de Samotracia', 'Mona Lisa · Winged Victory of Samothrace'), dato: L('El museo más visitado del mundo. Tendrías que caminar kilómetros para verlo entero.', 'The most visited museum in the world. You\'d have to walk for kilometers to see it all.') },
    { nombre: L('Museo del Prado', 'Museo del Prado'), ciudad: L('Madrid, España', 'Madrid, Spain'), color: 'var(--yellow-deep)', joya: L('Las Meninas · El jardín de las delicias', 'Las Meninas · The Garden of Earthly Delights'), dato: L('La mejor colección de Velázquez, Goya y El Bosco del planeta.', 'The finest collection of Velázquez, Goya and Bosch on the planet.') },
    { nombre: 'MoMA', ciudad: L('Nueva York, EE. UU.', 'New York, USA'), color: 'var(--ink)', joya: L('La noche estrellada · Las señoritas de Avignon', 'The Starry Night · Les Demoiselles d\'Avignon'), dato: L('El templo del arte moderno: define qué cuenta como "moderno" desde 1929.', 'The temple of modern art: it has defined what counts as "modern" since 1929.') },
    { nombre: L('Galería Uffizi', 'Uffizi Gallery'), ciudad: L('Florencia, Italia', 'Florence, Italy'), color: 'var(--lilac-deep)', joya: L('El nacimiento de Venus · La Primavera', 'The Birth of Venus · La Primavera'), dato: L('Corazón del Renacimiento. Botticelli, Leonardo y Miguel Ángel bajo un mismo techo.', 'The heart of the Renaissance. Botticelli, Leonardo and Michelangelo under one roof.') },
    { nombre: 'Rijksmuseum', ciudad: L('Ámsterdam, Países Bajos', 'Amsterdam, Netherlands'), color: 'var(--red-deep)', joya: L('La ronda de noche · La lechera', 'The Night Watch · The Milkmaid'), dato: L('La casa de Rembrandt y Vermeer; el Siglo de Oro neerlandés en estado puro.', 'The home of Rembrandt and Vermeer; the Dutch Golden Age in its purest form.') },
    { nombre: L('Museo Reina Sofía', 'Museo Reina Sofía'), ciudad: L('Madrid, España', 'Madrid, Spain'), color: 'var(--ink)', joya: 'Guernica', dato: L('Alberga el "Guernica" de Picasso, custodiado como un símbolo nacional.', 'Home to Picasso\'s "Guernica", guarded as a national symbol.') },
    { nombre: 'Tate Modern', ciudad: L('Londres, Reino Unido', 'London, United Kingdom'), color: 'var(--violet-deep)', joya: 'Rothko · Warhol · Hockney', dato: L('Una antigua central eléctrica convertida en el museo de arte contemporáneo más visitado.', 'A former power station turned into the most visited contemporary-art museum.') },
    { nombre: 'The Met', ciudad: L('Nueva York, EE. UU.', 'New York, USA'), color: 'var(--yellow)', joya: L('5.000 años de arte mundial', '5,000 years of world art'), dato: L('Más de dos millones de obras: de templos egipcios a arte contemporáneo.', 'Over two million works: from Egyptian temples to contemporary art.') },
  ];

  const premios = [
    { nombre: L('León de Oro', 'Golden Lion'), donde: L('Bienal de Venecia · Italia', 'Venice Biennale · Italy'), desde: '1895', desc: L('El máximo reconocimiento de la bienal de arte más antigua e influyente del mundo.', 'The highest honor of the oldest and most influential art biennale in the world.') },
    { nombre: 'Turner Prize', donde: L('Tate · Reino Unido', 'Tate · United Kingdom'), desde: '1984', desc: L('El premio que define la conversación del arte contemporáneo británico — siempre polémico.', 'The prize that defines the British contemporary-art conversation — always controversial.') },
    { nombre: 'Praemium Imperiale', donde: L('Japón', 'Japan'), desde: '1988', desc: L('Conocido como "el Nobel del arte": premia trayectorias en pintura, escultura, arquitectura y música.', 'Known as "the Nobel of art": it honors careers in painting, sculpture, architecture and music.') },
    { nombre: L('Premio Velázquez', 'Velázquez Prize'), donde: L('España · Iberoamérica', 'Spain · Ibero-America'), desde: '2002', desc: L('El mayor galardón a las artes plásticas en el ámbito iberoamericano.', 'The greatest award for the visual arts in the Ibero-American sphere.') },
    { nombre: L('Premio Marcel Duchamp', 'Marcel Duchamp Prize'), donde: L('Francia', 'France'), desde: '2000', desc: L('Distingue a artistas emergentes y de media carrera radicados en Francia.', 'Recognizes emerging and mid-career artists based in France.') },
    { nombre: 'Hugo Boss Prize', donde: L('Guggenheim · EE. UU.', 'Guggenheim · USA'), desde: '1996', desc: L('Reconoce el trabajo más arriesgado y experimental sin importar edad ni nacionalidad.', 'Recognizes the most daring and experimental work regardless of age or nationality.') },
  ];

  const movimientos = [
    { ano: '1400', nombre: L('Renacimiento', 'Renaissance'), color: 'var(--yellow-deep)' },
    { ano: '1600', nombre: L('Barroco', 'Baroque'), color: 'var(--ink)' },
    { ano: '1770', nombre: L('Neoclásico', 'Neoclassical'), color: 'var(--ink-soft)' },
    { ano: '1840', nombre: L('Impresionismo', 'Impressionism'), color: 'var(--lilac)' },
    { ano: '1905', nombre: L('Vanguardias', 'Avant-gardes'), color: 'var(--red)' },
    { ano: '1945', nombre: L('Expr. Abstracto', 'Abstract Expr.'), color: 'var(--ink)' },
    { ano: '1960', nombre: 'Pop Art', color: 'var(--lilac)' },
    { ano: '1980', nombre: L('Neoexpresionismo', 'Neo-Expressionism'), color: 'var(--red)' },
    { ano: L('Hoy', 'Today'), nombre: L('Emergente', 'Emerging'), color: 'var(--red-deep)' },
  ];

  return { datosTicker, datosCuriosos, artistas, cuadrosCaros, museos, premios, movimientos };
}
