import { wiki } from '@/lib/atlas';

export const articles = [
  {
    slug: 'primera-galeria-historia',
    date: '18 jun 2026',
    title: 'De la cueva a la galería blanca: 40.000 años de exponer arte',
    excerpt: 'Antes de las salas de paredes blancas y los catálogos glossy, el arte ya se exponía. Solo que el espacio era una roca y la iluminación era fuego.',
    image: wiki('Bisonte Magdaleniense polícromo.jpg', 1200),
    imageAlt: 'Bisonte pintado en la cueva de Altamira, España, circa 15.000 a.C.',
    imageCaption: 'Cueva de Altamira, España · circa 15.000 a.C. · Dominio público',
    body: [
      'La primera "galería de arte" de la humanidad no tenía paredes blancas ni ficha de catálogo. Era una cueva en Sulawesi, Indonesia, donde alguien — hace más de 45.500 años — pintó un cerdo con pigmento rojo sobre roca. No había nombre del artista. No había precio mínimo. Solo la necesidad urgente de dejar algo marcado.',
      'En Europa, las cuevas de Altamira (España) y Lascaux (Francia) representan ese mismo impulso, entre 15.000 y 20.000 años atrás. Los bisontes de Altamira fueron pintados con tal precisión anatómica que cuando se descubrieron en 1879, los arqueólogos no querían creer que fueran prehistóricos. Parecían demasiado buenos para ser tan viejos.',
      'El salto a la galería como institución viene mucho después. En la Grecia clásica, el Partenón tenía una "pinacotheca" — literalmente "lugar donde se guardan las tablas pintadas" — en el ala norte de los Propíleos. Era el primer espacio arquitectónico diseñado específicamente para contener imágenes. Siglo V antes de Cristo.',
      'Las colecciones privadas del Renacimiento italiano — los Medici en Florencia, los Borghese en Roma — fueron el siguiente escalón: arte acumulado como símbolo de poder, mostrado a visitas selectas. La palabra "galleria" en italiano designaba literalmente el corredor largo donde colgaban esas obras.',
      'La primera galería comercial moderna tal como la conocemos aparece en París alrededor de 1777, con la Galerie Lebrun: un espacio donde los artistas podían vender directamente, sin depender del mecenazgo de la nobleza. Fue revolucionario. Dieciseis años después, en 1793, el Louvre abre sus puertas al público general durante la Revolución Francesa — la primera vez en la historia que una colección de arte se declara patrimonio de todos, no de un rey.',
      'En América Latina, el hito llega en 1935: Carolina Amor funda en Ciudad de México la Galería de Arte Mexicano, la primera galería comercial del continente dedicada a arte contemporáneo. En Colombia, las primeras galerías aparecen recién en la década de 1950.',
      'Lo que conecta la cueva de Sulawesi con una galería en Bogotá o Ciudad de México es exactamente lo mismo: alguien decidió que una imagen valía la pena ser vista. Todo lo demás — las paredes blancas, los catálogos, las subastas, los NFTs — es infraestructura al servicio de ese gesto original.',
    ],
  },
  {
    slug: 'datos-curiosos-arte',
    date: '12 jun 2026',
    title: 'Once cosas del arte que nadie te enseñó en el colegio',
    excerpt: 'Van Gogh vendió casi nada en vida. El arte estuvo en los Juegos Olímpicos. Y un pigmento popular en el siglo XVIII se hacía de momias molidas.',
    image: wiki('Van Gogh - Starry Night - Google Art Project.jpg', 1200),
    imageAlt: 'La noche estrellada de Vincent van Gogh, 1889, MoMA Nueva York',
    imageCaption: 'La noche estrellada · Vincent van Gogh · 1889 · MoMA, Nueva York · Dominio público',
    body: [
      'Van Gogh vendió casi nada en vida. El mito dice "una sola obra" pero la realidad es apenas un poco mejor: se estima que vendió entre 1 y 4 pinturas durante sus diez años activos como artista, de las más de 2.000 obras que produjo. Murió en 1890 prácticamente en la pobreza. En 1990, su "Retrato del Dr. Gachet" se vendió por 82,5 millones de dólares. El mismo cuadro.',
      'El nombre completo de Picasso tiene 23 palabras. Se llamaba: Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Crispiniano de la Santísima Trinidad Ruiz y Picasso. Los nombres eran de santos y parientes, según la costumbre española. Usó "Picasso" — apellido de su madre — porque era más inusual que Ruiz.',
      'El arte estuvo en los Juegos Olímpicos entre 1912 y 1948. En serio. Había competencias de pintura, escultura, arquitectura, literatura y música, todas con medallas. La única condición era que la obra estuviera "inspirada en el deporte". La categoría se eliminó porque varios de los competidores eran artistas profesionales, lo que violaba el principio amateur de los Juegos.',
      'Un pigmento muy popular en Europa entre los siglos XVI y XIX se llamaba "mummy brown". Se obtenía, literalmente, de momias egipcias molidas y mezcladas con aceite. El color era un marrón cálido y transparente muy apreciado para veladuras. Cuando los artistas victorianos descubrieron de qué estaba hecho, muchos organizaron funerales improvisados para sus tubos de pintura.',
      'La Mona Lisa estuvo desaparecida dos años. Fue robada del Louvre en agosto de 1911 por Vincenzo Peruggia, un italiano que trabajó en el museo y simplemente la sacó bajo su abrigo. El robo no se descubrió hasta al día siguiente. Peruggia la tuvo guardada en su apartamento de París durante más de dos años antes de intentar venderla en Florencia. Lo arrestaron en 1913.',
      'El Grito no es una sola pintura. Edvard Munch creó al menos cinco versiones entre 1893 y 1910: dos pinturas al óleo, dos pasteles y un dibujo. La más conocida está en la Galería Nacional de Oslo. En 2012, una versión en pastel se vendió en Sotheby\'s por 119,9 millones de dólares.',
      'Existe un museo dedicado exclusivamente a falsificaciones. El Museum of Art Fakes en Viena exhibe copias y falsificaciones de obras famosas, no como fraude sino como reflexión sobre la autenticidad, el valor y la percepción en el arte.',
      'Miguel Ángel pintó la Capilla Sixtina de pie, no acostado. La imagen del artista tumbado boca arriba es un mito popular. Los registros históricos y su propia poesía confirman que trabajó de pie, con el cuello doblado hacia arriba durante cuatro años. Desarrolló una afección visual permanente que lo obligó a leer con el papel sobre la cabeza.',
      'El cuadro más visto del mundo no está en ningún museo de arte. Es la imagen de fondo de escritorio predeterminada de Windows XP — una fotografía de una colina verde en Sonoma, California, llamada "Bliss". La tomó Charles O\'Rear en 1996. Se estima que fue vista por más de mil millones de personas.',
      'Rembrandt firmaba sus obras con solo su nombre de pila. En una época en que los artistas usaban apellidos completos, Rembrandt Harmenszoon van Rijn decidió que "Rembrandt" era suficiente. Lo tomó de los grandes maestros italianos que conocía — Leonardo, Rafael, Michelangelo — que también usaban un solo nombre.',
      'La pintura más antigua con un nombre de artista conocido tiene más de 4.500 años. Se llama "Iri-hor" y es un graffiti en una roca en el Valle de los Reyes, Egipto. Antes de eso, el arte era anónimo por definición — la obra importaba, no quien la hizo.',
    ],
  },
  {
    slug: 'subastas-records-historia',
    date: '05 jun 2026',
    title: 'Los números que redefinieron el mercado: las subastas más épicas de la historia',
    excerpt: '$236 millones por un Klimt. $181 millones por un Pollock. Cómo las casas de subasta convirtieron el arte en el activo más impredecible del mundo.',
    image: wiki('Gustav Klimt 046.jpg', 900),
    imageAlt: 'El beso de Gustav Klimt, 1908, Belvedere, Viena',
    imageCaption: 'El beso · Gustav Klimt · 1908 · Belvedere, Viena · Dominio público',
    body: [
      'En noviembre de 2025, "Retrato de Elisabeth Lederer" de Gustav Klimt se vendió en Sotheby\'s Nueva York por 236,4 millones de dólares. Fue el récord absoluto para una obra de arte moderno en subasta. El cuadro representa a la esposa de un coleccionista vienés que fue asesinado en un campo de concentración nazi en 1944. La obra había sido confiscada por los nazis en 1938 y tardó décadas en ser restituida a los herederos de la familia.',
      'Tres meses antes, una obra de Jackson Pollock llamada "Number 7A, 1948" — un dripping de la época más pura del expresionismo abstracto — alcanzó los 181,2 millones de dólares. Es el precio más alto jamás pagado por una obra americana.',
      'Los récords en subasta no son solo grandes números: son indicadores de cómo el mercado del arte procesa historia, trauma, escasez y deseo al mismo tiempo. El Klimt de Sotheby\'s vale lo que vale no solo por la pintura, sino por todo lo que la rodeó: el nazismo, la restitución, la rareza de un Klimt disponible. El mercado cotiza el relato tanto como la obra.',
      'El récord histórico absoluto sigue siendo "Salvator Mundi", atribuido a Leonardo da Vinci, que se vendió en Christie\'s en 2017 por 450,3 millones de dólares. Comprado por un comprador anónimo que resultó ser el gobierno de Arabia Saudita. Desde entonces, la obra no se ha vuelto a exhibir públicamente. Nadie sabe exactamente dónde está.',
      'Jean-Michel Basquiat rompió su propio récord en 2017 cuando su "Untitled" (1982) alcanzó los 110,5 millones en Sotheby\'s Nueva York. Fue el primer artista americano en superar los 100 millones en subasta. Basquiat murió de sobredosis en 1988, a los 27 años. Había empezado su carrera pintando grafitis en el Lower East Side de Manhattan.',
      'Lo que estos números dicen del arte emergente es esto: el mercado tiene memoria larga. Los artistas que hoy cuestan poco pueden costar todo en cincuenta años, o en diez. La diferencia entre Basquiat pintando graffiti en 1980 y Basquiat en Sotheby\'s en 2017 no es el artista — es el tiempo y la gente que creyó antes.',
      'Las grandes casas de subasta — Christie\'s, Sotheby\'s, Phillips — reportaron ventas combinadas de más de 14.000 millones de dólares en 2023. Es un mercado más grande que muchas industrias tradicionales, y buena parte de ese dinero fluye desde los récords hacia abajo: cuando un artista rompe un techo, sube el piso para todos los que trabajan en su registro.',
    ],
  },
  {
    slug: 'mercado-arte-emergente-2026',
    date: '28 may 2026',
    title: 'El coleccionista cambió: lo que los datos del mercado de 2026 dicen sobre el arte emergente',
    excerpt: 'El 72% de los coleccionistas activos busca nuevos talentos. El 71% de los menores de 37 años compró arte online el último año. El mercado no espera a las ferias.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80&fit=crop',
    imageAlt: 'Galería de arte contemporánea con paredes blancas y visitantes',
    imageCaption: 'Galería contemporánea · Foto: Unsplash (uso libre)',
    body: [
      'El informe del mercado del arte de 2026 confirmó algo que muchas galerías pequeñas ya sabían por instinto: el perfil del coleccionista cambió. El 72% de los coleccionistas activos declara sentirse atraído por nuevos talentos, y el 51% de las galerías los considera su prioridad comercial principal. La figura del coleccionista conservador que solo compra nombres establecidos sigue existiendo, pero ya no define el mercado.',
      'El dato más significativo es generacional. El 71% de los coleccionistas menores de 37 años compró arte online en el último año. Para esta franja, la galería física es complementaria, no obligatoria. Descubrieron al artista en Instagram, leyeron sobre él en un blog, y compraron sin pisar un piso de parquet.',
      'El mercado se está polarizando en dos extremos: en la cima, un número reducido de obras y artistas ya consagrados que alcanzan récords históricos en las grandes casas de subasta. En la base, una franja creciente de arte emergente accesible, comprado por coleccionistas que empiezan con presupuestos pequeños pero intención firme.',
      'El rango más activo del mercado emergente está entre los 500 y los 5.000 dólares por pieza. Es el umbral donde el comprador puede tomar una decisión sin consultarla dos semanas, y donde el artista puede empezar a vivir de su trabajo si vende consistentemente.',
      'Las exposiciones híbridas — espacio físico más galería virtual — son ya estándar en 2026. Las plataformas que solo existen online tienen alcance global pero pierden la dimensión táctil de la obra. Las que solo existen físicamente tienen presencia pero pierden alcance. El modelo que está ganando combina ambos: un punto de encuentro físico por temporada con presencia digital permanente.',
      'Los NFTs, que en 2021 parecían redefinir todo, encontraron su lugar real en 2026: no como sustituto del arte físico, sino como capa de autenticidad y trazabilidad sobre él. Un certificado blockchain que documenta la procedencia de una obra tiene valor real. Una imagen digital vendida como activo especulativo sin respaldo físico, mucho menos.',
      'Para los artistas emergentes, la lectura práctica de estos datos es simple: el mercado está buscando lo que ellos producen. El problema no es la demanda — es la visibilidad. El comprador nuevo quiere descubrir. El artista nuevo quiere ser encontrado. Lo que falta, casi siempre, es el espacio con el criterio suficiente para presentar al uno al otro.',
    ],
  },
  {
    slug: 'por-que-arte-no-pierde-valor',
    date: '20 may 2026',
    title: 'Por qué el arte sobrevive a las crisis económicas mejor que casi cualquier otro activo',
    excerpt: 'En 2008, el mercado financiero colapsó. El arte también cayó, pero se recuperó más rápido. Hay una razón histórica para eso.',
    image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80&fit=crop',
    imageAlt: 'Pintura abstracta en gran formato sobre pared de galería',
    imageCaption: 'Arte abstracto contemporáneo · Foto: Unsplash (uso libre)',
    body: [
      'Cuando los mercados financieros entran en pánico, el capital busca refugios. El oro es el más conocido. El arte es el menos obvio, pero tiene un historial más largo que casi cualquier instrumento financiero moderno.',
      'Durante la Gran Depresión de los años 30, las colecciones de arte de grandes familias estadounidenses se mantuvieron. En algunos casos, obras que se creían invendibles encontraron compradores europeos que querían sacar capital de un continente al borde de la guerra. El arte cruzó fronteras cuando el dinero no podía.',
      'En 2008, el mercado del arte cayó junto con todo lo demás. Pero la caída fue más moderada y la recuperación fue más rápida. Entre 2009 y 2014, el índice de precios del arte contemporáneo subió más del 70%, superando en ese período a la bolsa de valores de casi cualquier mercado desarrollado.',
      'La razón estructural es simple: el arte es escaso por definición. Una obra específica de un artista específico no puede reproducirse en cantidad. Cuando muere un artista, su catálogo queda fijo para siempre. El mercado puede subir o bajar, pero la cantidad de Modiglianis disponibles no cambia. Esa escasez estructural funciona como piso.',
      'El caso de El Greco ilustra el punto mejor que ningún otro. Durante casi dos siglos después de su muerte en 1614, sus obras estaban devaluadas: el estilo considerado "extravagante" y "distorsionado" no encajaba con el gusto académico europeo. Se vendían barato. En el siglo XIX, los impresionistas españoles y luego Cézanne "redescubrieron" su trabajo y el mercado lo recalibró completamente. Los que compraron El Greco barato en el siglo XVIII hicieron una de las mejores inversiones de la historia sin saberlo.',
      'Van Gogh es el caso extremo: murió casi sin vender nada. Hoy es el artista con más obras en el top 50 de ventas en subasta de la historia. El tiempo fue el único factor que cambió.',
      'Nada de esto significa que comprar arte sea una inversión financiera simple o predecible. La mayoría de las obras compradas hoy no valdrán más en veinte años. Pero las que sí — las que tienen detrás un artista genuino, una obra coherente y un momento de descubrimiento documentado — tienden a comportarse como el oro: como reserva de valor que sobrevive a las tormentas.',
      'El coleccionista inteligente no compra para vender. Compra porque la obra le importa, y eso, paradójicamente, es lo que más le protege: si el mercado cae, todavía tiene algo en la pared que vale la pena mirar.',
    ],
  },
  {
    slug: 'color-historia-pigmentos',
    date: '10 may 2026',
    title: 'La historia violenta y fascinante del color: cómo los artistas consiguieron sus pigmentos',
    excerpt: 'El azul ultramarino valía más que el oro. El verde esmeralda era venenoso. El blanco de plomo mataba a quien lo usaba. Pintar siempre tuvo un costo.',
    image: wiki('Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg', 900),
    imageAlt: 'La Gioconda de Leonardo da Vinci, circa 1503–1519, Museo del Louvre, París',
    imageCaption: 'La Gioconda · Leonardo da Vinci · circa 1503 · Louvre, París · Dominio público',
    body: [
      'Antes de que existiera el tubo de pintura, conseguir un color específico podía costar fortunas, años de viaje, o la vida. La historia del arte es también la historia de cómo los seres humanos persiguieron el color con una obsesión que hoy resulta difícil de imaginar.',
      'El azul ultramarino — ese azul profundo que aparece en los mantos de la Virgen en casi toda la pintura medieval y renacentista — se fabricaba a partir del lapislázuli, una piedra semipreciosa que solo existía en una sola mina en el mundo: en las montañas de Badajshan, en lo que hoy es Afganistán. Había que extraerla, transportarla a través de Asia Central y Europa, y molerla durante semanas. Era más cara que el oro por peso. Los contratos de encargo de la época especificaban exactamente cuántos gramos de ultramarino podía usar el artista y en qué partes de la obra.',
      'El verde esmeralda, popular en la pintura del siglo XIX, era una combinación de arsénico y cobre que producía un verde brillante sin precedente. También era altamente tóxico. Se cree que las habitaciones tapizadas con papel pintado de ese color — que se fabricaba con el mismo pigmento — contribuyeron a la mala salud de Napoleón en su exilio en Santa Elena. Algunos historiadores sospechan que el arsénico del papel de sus paredes fue un factor en su muerte.',
      'El blanco de plomo fue el blanco estándar de la pintura europea desde la antigüedad hasta el siglo XX. Era brillante, opaco y secaba bien. También era lentamente letal. La exposición prolongada al plomo provoca daño neurológico acumulativo. Goya, que usó grandes cantidades en su técnica, desarrolló una sordera progresiva y un estado mental que algunos historiadores atribuyen parcialmente a la intoxicación crónica. Sus "Pinturas negras" — los murales que cubrió en su propia casa — fueron hechos con plomo.',
      'El amarillo de Nápoles, usado desde el Renacimiento, se fabricaba con antimoniato de plomo: también tóxico, también brillante, también difícil de reemplazar. El pigmento índigo — el azul más oscuro de la pintura asiática y europea — dependía de una planta tropical que se cultivaba principalmente con trabajo esclavo en las colonias. El comercio del arte y el comercio de personas estuvieron conectados por el color.',
      'El primer color sintético de la historia moderna fue el azul de Prusia, descubierto por accidente en Berlín alrededor de 1704. Un fabricante de pinturas intentaba hacer rojo y obtuvo azul. Cambió el mercado del color para siempre: por primera vez, un tono específico podía producirse de forma consistente, barata y en cantidad. El impresionismo — con su obsesión por capturar la luz — no hubiera existido sin la revolución de los pigmentos sintéticos del siglo XIX.',
      'Hoy, los tubos de óleo en cualquier ferretería de arte contienen colores que en el Renacimiento habrían costado el equivalente de meses de trabajo. El azul ultramarino artificial, sintetizado por primera vez en 1828, es indistinguible al ojo del original y cuesta céntimos. Lo que los artistas renacentistas negociaban por gramos, hoy se compra por kilos. Pero algo se perdió en esa democratización: el peso de saber que ese azul venía de un lugar específico en el mundo, transportado por manos específicas, valioso por su rareza absoluta.',
    ],
  },
];

export function getArticleBySlug(slug) {
  return articles.find((a) => a.slug === slug);
}
