import { wiki } from '@/lib/atlas';

// Artículos del blog (bilingüe ES/EN). L(es, en) elige según idioma.
export function getArticles(locale) {
  const L = (es, en) => (locale === 'en' ? en : es);

  return [
    {
      slug: 'primera-galeria-historia',
      date: L('18 jun 2026', 'Jun 18, 2026'),
      title: L('De la cueva a la galería blanca: 40.000 años de exponer arte', 'From the cave to the white cube: 40,000 years of exhibiting art'),
      excerpt: L('Antes de las salas de paredes blancas y los catálogos glossy, el arte ya se exponía. Solo que el espacio era una roca y la iluminación era fuego.', 'Before white-walled rooms and glossy catalogues, art was already being exhibited. Only the space was a rock and the lighting was fire.'),
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/White_Cube_Gallery_C13_at_Art_Basel_2025.jpg/960px-White_Cube_Gallery_C13_at_Art_Basel_2025.jpg',
      imageAlt: L('White Cube Gallery en Art Basel 2025', 'White Cube Gallery at Art Basel 2025'),
      imageCaption: L('White Cube Gallery · Art Basel 2025 · Dominio público', 'White Cube Gallery · Art Basel 2025 · Public domain'),
      body: [
        L('La primera "galería de arte" de la humanidad no tenía paredes blancas ni ficha de catálogo. Era una cueva en Sulawesi, Indonesia, donde alguien — hace más de 45.500 años — pintó un cerdo con pigmento rojo sobre roca. No había nombre del artista. No había precio mínimo. Solo la necesidad urgente de dejar algo marcado.', 'Humanity\'s first "art gallery" had no white walls or catalogue label. It was a cave in Sulawesi, Indonesia, where someone — more than 45,500 years ago — painted a pig in red pigment on rock. There was no artist\'s name. No minimum price. Just the urgent need to leave something marked.'),
        L('En Europa, las cuevas de Altamira (España) y Lascaux (Francia) representan ese mismo impulso, entre 15.000 y 20.000 años atrás. Los bisontes de Altamira fueron pintados con tal precisión anatómica que cuando se descubrieron en 1879, los arqueólogos no querían creer que fueran prehistóricos. Parecían demasiado buenos para ser tan viejos.', 'In Europe, the caves of Altamira (Spain) and Lascaux (France) represent that same impulse, between 15,000 and 20,000 years ago. The bison of Altamira were painted with such anatomical precision that when they were discovered in 1879, archaeologists refused to believe they were prehistoric. They looked too good to be that old.'),
        L('El salto a la galería como institución viene mucho después. En la Grecia clásica, el Partenón tenía una "pinacotheca" — literalmente "lugar donde se guardan las tablas pintadas" — en el ala norte de los Propíleos. Era el primer espacio arquitectónico diseñado específicamente para contener imágenes. Siglo V antes de Cristo.', 'The leap to the gallery as an institution came much later. In classical Greece, the Parthenon had a "pinacotheca" — literally "a place where painted panels are kept" — in the north wing of the Propylaea. It was the first architectural space designed specifically to hold images. Fifth century BC.'),
        L('Las colecciones privadas del Renacimiento italiano — los Medici en Florencia, los Borghese en Roma — fueron el siguiente escalón: arte acumulado como símbolo de poder, mostrado a visitas selectas. La palabra "galleria" en italiano designaba literalmente el corredor largo donde colgaban esas obras.', 'The private collections of the Italian Renaissance — the Medici in Florence, the Borghese in Rome — were the next step: art accumulated as a symbol of power, shown to select visitors. The word "galleria" in Italian literally named the long corridor where those works hung.'),
        L('La primera galería comercial moderna tal como la conocemos aparece en París alrededor de 1777, con la Galerie Lebrun: un espacio donde los artistas podían vender directamente, sin depender del mecenazgo de la nobleza. Fue revolucionario. Dieciseis años después, en 1793, el Louvre abre sus puertas al público general durante la Revolución Francesa — la primera vez en la historia que una colección de arte se declara patrimonio de todos, no de un rey.', 'The first modern commercial gallery as we know it appeared in Paris around 1777, with the Galerie Lebrun: a space where artists could sell directly, without depending on the patronage of the nobility. It was revolutionary. Sixteen years later, in 1793, the Louvre opened its doors to the general public during the French Revolution — the first time in history that an art collection was declared the heritage of everyone, not of a king.'),
        L('En América Latina, el hito llega en 1935: Carolina Amor funda en Ciudad de México la Galería de Arte Mexicano, la primera galería comercial del continente dedicada a arte contemporáneo. En Colombia, las primeras galerías aparecen recién en la década de 1950.', 'In Latin America, the milestone came in 1935: Carolina Amor founded the Galería de Arte Mexicano in Mexico City, the continent\'s first commercial gallery dedicated to contemporary art. In Colombia, the first galleries appeared only in the 1950s.'),
        L('Lo que conecta la cueva de Sulawesi con una galería en Bogotá o Ciudad de México es exactamente lo mismo: alguien decidió que una imagen valía la pena ser vista. Todo lo demás — las paredes blancas, los catálogos, las subastas, los NFTs — es infraestructura al servicio de ese gesto original.', 'What connects the Sulawesi cave with a gallery in Bogotá or Mexico City is exactly the same: someone decided that an image was worth being seen. Everything else — the white walls, the catalogues, the auctions, the NFTs — is infrastructure in service of that original gesture.'),
      ],
    },
    {
      slug: 'datos-curiosos-arte',
      date: L('12 jun 2026', 'Jun 12, 2026'),
      title: L('Once cosas del arte que nadie te enseñó en el colegio', 'Eleven things about art no one taught you in school'),
      excerpt: L('Van Gogh vendió casi nada en vida. El arte estuvo en los Juegos Olímpicos. Y un pigmento popular en el siglo XVIII se hacía de momias molidas.', 'Van Gogh sold almost nothing in his lifetime. Art was in the Olympics. And a popular 18th-century pigment was made from ground mummies.'),
      image: wiki('Van Gogh - Starry Night - Google Art Project.jpg', 1200),
      imageAlt: L('La noche estrellada de Vincent van Gogh, 1889, MoMA Nueva York', 'The Starry Night by Vincent van Gogh, 1889, MoMA New York'),
      imageCaption: L('La noche estrellada · Vincent van Gogh · 1889 · MoMA, Nueva York · Dominio público', 'The Starry Night · Vincent van Gogh · 1889 · MoMA, New York · Public domain'),
      body: [
        L('Van Gogh vendió casi nada en vida. El mito dice "una sola obra" pero la realidad es apenas un poco mejor: se estima que vendió entre 1 y 4 pinturas durante sus diez años activos como artista, de las más de 2.000 obras que produjo. Murió en 1890 prácticamente en la pobreza. En 1990, su "Retrato del Dr. Gachet" se vendió por 82,5 millones de dólares. El mismo cuadro.', 'Van Gogh sold almost nothing in his lifetime. The myth says "a single work" but reality is only slightly better: he is estimated to have sold between 1 and 4 paintings during his ten active years as an artist, out of more than 2,000 works he produced. He died in 1890 practically in poverty. In 1990, his "Portrait of Dr. Gachet" sold for 82.5 million dollars. The same painting.'),
        L('El nombre completo de Picasso tiene 23 palabras. Se llamaba: Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Crispiniano de la Santísima Trinidad Ruiz y Picasso. Los nombres eran de santos y parientes, según la costumbre española. Usó "Picasso" — apellido de su madre — porque era más inusual que Ruiz.', 'Picasso\'s full name has 23 words. He was called: Diego José Francisco de Paula Juan Nepomuceno María de los Remedios Crispiniano de la Santísima Trinidad Ruiz y Picasso. The names came from saints and relatives, per Spanish custom. He used "Picasso" — his mother\'s surname — because it was more unusual than Ruiz.'),
        L('El arte estuvo en los Juegos Olímpicos entre 1912 y 1948. En serio. Había competencias de pintura, escultura, arquitectura, literatura y música, todas con medallas. La única condición era que la obra estuviera "inspirada en el deporte". La categoría se eliminó porque varios de los competidores eran artistas profesionales, lo que violaba el principio amateur de los Juegos.', 'Art was in the Olympic Games between 1912 and 1948. Seriously. There were competitions in painting, sculpture, architecture, literature and music, all with medals. The only condition was that the work be "inspired by sport". The category was dropped because several competitors were professional artists, which violated the amateur principle of the Games.'),
        L('Un pigmento muy popular en Europa entre los siglos XVI y XIX se llamaba "mummy brown". Se obtenía, literalmente, de momias egipcias molidas y mezcladas con aceite. El color era un marrón cálido y transparente muy apreciado para veladuras. Cuando los artistas victorianos descubrieron de qué estaba hecho, muchos organizaron funerales improvisados para sus tubos de pintura.', 'A very popular pigment in Europe between the 16th and 19th centuries was called "mummy brown". It was obtained, literally, from ground Egyptian mummies mixed with oil. The color was a warm, transparent brown much prized for glazes. When Victorian artists found out what it was made of, many held improvised funerals for their paint tubes.'),
        L('La Mona Lisa estuvo desaparecida dos años. Fue robada del Louvre en agosto de 1911 por Vincenzo Peruggia, un italiano que trabajó en el museo y simplemente la sacó bajo su abrigo. El robo no se descubrió hasta al día siguiente. Peruggia la tuvo guardada en su apartamento de París durante más de dos años antes de intentar venderla en Florencia. Lo arrestaron en 1913.', 'The Mona Lisa was missing for two years. It was stolen from the Louvre in August 1911 by Vincenzo Peruggia, an Italian who had worked at the museum and simply carried it out under his coat. The theft wasn\'t discovered until the next day. Peruggia kept it in his Paris apartment for more than two years before trying to sell it in Florence. He was arrested in 1913.'),
        L('El Grito no es una sola pintura. Edvard Munch creó al menos cinco versiones entre 1893 y 1910: dos pinturas al óleo, dos pasteles y un dibujo. La más conocida está en la Galería Nacional de Oslo. En 2012, una versión en pastel se vendió en Sotheby\'s por 119,9 millones de dólares.', 'The Scream is not a single painting. Edvard Munch created at least five versions between 1893 and 1910: two oil paintings, two pastels and a drawing. The best-known is in the National Gallery of Oslo. In 2012, a pastel version sold at Sotheby\'s for 119.9 million dollars.'),
        L('Existe un museo dedicado exclusivamente a falsificaciones. El Museum of Art Fakes en Viena exhibe copias y falsificaciones de obras famosas, no como fraude sino como reflexión sobre la autenticidad, el valor y la percepción en el arte.', 'There is a museum devoted entirely to forgeries. The Museum of Art Fakes in Vienna exhibits copies and forgeries of famous works, not as fraud but as a reflection on authenticity, value and perception in art.'),
        L('Miguel Ángel pintó la Capilla Sixtina de pie, no acostado. La imagen del artista tumbado boca arriba es un mito popular. Los registros históricos y su propia poesía confirman que trabajó de pie, con el cuello doblado hacia arriba durante cuatro años. Desarrolló una afección visual permanente que lo obligó a leer con el papel sobre la cabeza.', 'Michelangelo painted the Sistine Chapel standing, not lying down. The image of the artist on his back is a popular myth. Historical records and his own poetry confirm he worked standing, neck bent upward, for four years. He developed a lasting vision problem that forced him to read with paper held above his head.'),
        L('El cuadro más visto del mundo no está en ningún museo de arte. Es la imagen de fondo de escritorio predeterminada de Windows XP — una fotografía de una colina verde en Sonoma, California, llamada "Bliss". La tomó Charles O\'Rear en 1996. Se estima que fue vista por más de mil millones de personas.', 'The most viewed image in the world is in no art museum. It\'s the default Windows XP desktop wallpaper — a photograph of a green hill in Sonoma, California, called "Bliss". Charles O\'Rear took it in 1996. It\'s estimated to have been seen by more than a billion people.'),
        L('Rembrandt firmaba sus obras con solo su nombre de pila. En una época en que los artistas usaban apellidos completos, Rembrandt Harmenszoon van Rijn decidió que "Rembrandt" era suficiente. Lo tomó de los grandes maestros italianos que conocía — Leonardo, Rafael, Michelangelo — que también usaban un solo nombre.', 'Rembrandt signed his works with only his first name. At a time when artists used full surnames, Rembrandt Harmenszoon van Rijn decided "Rembrandt" was enough. He took it from the great Italian masters he knew — Leonardo, Raphael, Michelangelo — who also went by a single name.'),
        L('La pintura más antigua con un nombre de artista conocido tiene más de 4.500 años. Se llama "Iri-hor" y es un graffiti en una roca en el Valle de los Reyes, Egipto. Antes de eso, el arte era anónimo por definición — la obra importaba, no quien la hizo.', 'The oldest artwork with a known artist\'s name is more than 4,500 years old. It\'s called "Iri-hor" and is a graffito on a rock in the Valley of the Kings, Egypt. Before that, art was anonymous by definition — the work mattered, not who made it.'),
      ],
    },
    {
      slug: 'subastas-records-historia',
      date: L('05 jun 2026', 'Jun 05, 2026'),
      title: L('Los números que redefinieron el mercado: las subastas más épicas de la historia', 'The numbers that redefined the market: the most epic auctions in history'),
      excerpt: L('$236 millones por un Klimt. $181 millones por un Pollock. Cómo las casas de subasta convirtieron el arte en el activo más impredecible del mundo.', '$236 million for a Klimt. $181 million for a Pollock. How auction houses turned art into the most unpredictable asset in the world.'),
      image: wiki('Gustav Klimt 046.jpg', 900),
      imageAlt: L('El beso de Gustav Klimt, 1908, Belvedere, Viena', 'The Kiss by Gustav Klimt, 1908, Belvedere, Vienna'),
      imageCaption: L('El beso · Gustav Klimt · 1908 · Belvedere, Viena · Dominio público', 'The Kiss · Gustav Klimt · 1908 · Belvedere, Vienna · Public domain'),
      body: [
        L('En noviembre de 2025, "Retrato de Elisabeth Lederer" de Gustav Klimt se vendió en Sotheby\'s Nueva York por 236,4 millones de dólares. Fue el récord absoluto para una obra de arte moderno en subasta. El cuadro representa a la esposa de un coleccionista vienés que fue asesinado en un campo de concentración nazi en 1944. La obra había sido confiscada por los nazis en 1938 y tardó décadas en ser restituida a los herederos de la familia.', 'In November 2025, Gustav Klimt\'s "Portrait of Elisabeth Lederer" sold at Sotheby\'s New York for 236.4 million dollars. It was the absolute record for a modern artwork at auction. The painting depicts the wife of a Viennese collector who was murdered in a Nazi concentration camp in 1944. The work had been confiscated by the Nazis in 1938 and took decades to be returned to the family\'s heirs.'),
        L('Tres meses antes, una obra de Jackson Pollock llamada "Number 7A, 1948" — un dripping de la época más pura del expresionismo abstracto — alcanzó los 181,2 millones de dólares. Es el precio más alto jamás pagado por una obra americana.', 'Three months earlier, a Jackson Pollock work called "Number 7A, 1948" — a drip from the purest era of abstract expressionism — reached 181.2 million dollars. It\'s the highest price ever paid for an American work.'),
        L('Los récords en subasta no son solo grandes números: son indicadores de cómo el mercado del arte procesa historia, trauma, escasez y deseo al mismo tiempo. El Klimt de Sotheby\'s vale lo que vale no solo por la pintura, sino por todo lo que la rodeó: el nazismo, la restitución, la rareza de un Klimt disponible. El mercado cotiza el relato tanto como la obra.', 'Auction records are not just big numbers: they\'re indicators of how the art market processes history, trauma, scarcity and desire at the same time. The Sotheby\'s Klimt is worth what it\'s worth not only for the painting, but for everything around it: Nazism, restitution, the rarity of an available Klimt. The market prices the story as much as the work.'),
        L('El récord histórico absoluto sigue siendo "Salvator Mundi", atribuido a Leonardo da Vinci, que se vendió en Christie\'s en 2017 por 450,3 millones de dólares. Comprado por un comprador anónimo que resultó ser el gobierno de Arabia Saudita. Desde entonces, la obra no se ha vuelto a exhibir públicamente. Nadie sabe exactamente dónde está.', 'The absolute all-time record remains "Salvator Mundi", attributed to Leonardo da Vinci, which sold at Christie\'s in 2017 for 450.3 million dollars. Bought by an anonymous buyer who turned out to be the government of Saudi Arabia. Since then, the work has not been publicly exhibited again. No one knows exactly where it is.'),
        L('Jean-Michel Basquiat rompió su propio récord en 2017 cuando su "Untitled" (1982) alcanzó los 110,5 millones en Sotheby\'s Nueva York. Fue el primer artista americano en superar los 100 millones en subasta. Basquiat murió de sobredosis en 1988, a los 27 años. Había empezado su carrera pintando grafitis en el Lower East Side de Manhattan.', 'Jean-Michel Basquiat broke his own record in 2017 when his "Untitled" (1982) reached 110.5 million at Sotheby\'s New York. He was the first American artist to surpass 100 million at auction. Basquiat died of an overdose in 1988, at 27. He had begun his career painting graffiti in Manhattan\'s Lower East Side.'),
        L('Lo que estos números dicen del arte emergente es esto: el mercado tiene memoria larga. Los artistas que hoy cuestan poco pueden costar todo en cincuenta años, o en diez. La diferencia entre Basquiat pintando graffiti en 1980 y Basquiat en Sotheby\'s en 2017 no es el artista — es el tiempo y la gente que creyó antes.', 'What these numbers say about emerging art is this: the market has a long memory. Artists who cost little today may cost everything in fifty years, or in ten. The difference between Basquiat painting graffiti in 1980 and Basquiat at Sotheby\'s in 2017 is not the artist — it\'s time and the people who believed first.'),
        L('Las grandes casas de subasta — Christie\'s, Sotheby\'s, Phillips — reportaron ventas combinadas de más de 14.000 millones de dólares en 2023. Es un mercado más grande que muchas industrias tradicionales, y buena parte de ese dinero fluye desde los récords hacia abajo: cuando un artista rompe un techo, sube el piso para todos los que trabajan en su registro.', 'The major auction houses — Christie\'s, Sotheby\'s, Phillips — reported combined sales of more than 14 billion dollars in 2023. It\'s a market bigger than many traditional industries, and much of that money flows from the records downward: when an artist breaks a ceiling, the floor rises for everyone working in their register.'),
      ],
    },
    {
      slug: 'mercado-arte-emergente-2026',
      date: L('28 may 2026', 'May 28, 2026'),
      title: L('El coleccionista cambió: lo que los datos del mercado de 2026 dicen sobre el arte emergente', 'The collector has changed: what the 2026 market data says about emerging art'),
      excerpt: L('El 72% de los coleccionistas activos busca nuevos talentos. El 71% de los menores de 37 años compró arte online el último año. El mercado no espera a las ferias.', '72% of active collectors seek new talent. 71% of those under 37 bought art online last year. The market doesn\'t wait for the fairs.'),
      image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&q=80&fit=crop',
      imageAlt: L('Galería de arte contemporánea con paredes blancas y visitantes', 'Contemporary art gallery with white walls and visitors'),
      imageCaption: L('Galería contemporánea · Foto: Unsplash (uso libre)', 'Contemporary gallery · Photo: Unsplash (free use)'),
      body: [
        L('El informe del mercado del arte de 2026 confirmó algo que muchas galerías pequeñas ya sabían por instinto: el perfil del coleccionista cambió. El 72% de los coleccionistas activos declara sentirse atraído por nuevos talentos, y el 51% de las galerías los considera su prioridad comercial principal. La figura del coleccionista conservador que solo compra nombres establecidos sigue existiendo, pero ya no define el mercado.', 'The 2026 art market report confirmed something many small galleries already knew by instinct: the collector\'s profile has changed. 72% of active collectors say they\'re drawn to new talent, and 51% of galleries consider them their main commercial priority. The figure of the conservative collector who only buys established names still exists, but it no longer defines the market.'),
        L('El dato más significativo es generacional. El 71% de los coleccionistas menores de 37 años compró arte online en el último año. Para esta franja, la galería física es complementaria, no obligatoria. Descubrieron al artista en Instagram, leyeron sobre él en un blog, y compraron sin pisar un piso de parquet.', 'The most significant figure is generational. 71% of collectors under 37 bought art online in the past year. For this group, the physical gallery is complementary, not mandatory. They discovered the artist on Instagram, read about them on a blog, and bought without ever setting foot on a parquet floor.'),
        L('El mercado se está polarizando en dos extremos: en la cima, un número reducido de obras y artistas ya consagrados que alcanzan récords históricos en las grandes casas de subasta. En la base, una franja creciente de arte emergente accesible, comprado por coleccionistas que empiezan con presupuestos pequeños pero intención firme.', 'The market is polarizing into two extremes: at the top, a small number of already-established works and artists reaching historic records at the major auction houses. At the base, a growing band of accessible emerging art, bought by collectors who start with small budgets but firm intent.'),
        L('El rango más activo del mercado emergente está entre los 500 y los 5.000 dólares por pieza. Es el umbral donde el comprador puede tomar una decisión sin consultarla dos semanas, y donde el artista puede empezar a vivir de su trabajo si vende consistentemente.', 'The most active range of the emerging market is between 500 and 5,000 dollars per piece. It\'s the threshold where the buyer can make a decision without deliberating for two weeks, and where the artist can start living off their work if they sell consistently.'),
        L('Las exposiciones híbridas — espacio físico más galería virtual — son ya estándar en 2026. Las plataformas que solo existen online tienen alcance global pero pierden la dimensión táctil de la obra. Las que solo existen físicamente tienen presencia pero pierden alcance. El modelo que está ganando combina ambos: un punto de encuentro físico por temporada con presencia digital permanente.', 'Hybrid exhibitions — physical space plus virtual gallery — are already standard in 2026. Platforms that exist only online have global reach but lose the tactile dimension of the work. Those that exist only physically have presence but lose reach. The winning model combines both: a physical meeting point per season with permanent digital presence.'),
        L('Los NFTs, que en 2021 parecían redefinir todo, encontraron su lugar real en 2026: no como sustituto del arte físico, sino como capa de autenticidad y trazabilidad sobre él. Un certificado blockchain que documenta la procedencia de una obra tiene valor real. Una imagen digital vendida como activo especulativo sin respaldo físico, mucho menos.', 'NFTs, which in 2021 seemed to redefine everything, found their real place in 2026: not as a substitute for physical art, but as a layer of authenticity and traceability over it. A blockchain certificate documenting a work\'s provenance has real value. A digital image sold as a speculative asset with no physical backing, far less.'),
        L('Para los artistas emergentes, la lectura práctica de estos datos es simple: el mercado está buscando lo que ellos producen. El problema no es la demanda — es la visibilidad. El comprador nuevo quiere descubrir. El artista nuevo quiere ser encontrado. Lo que falta, casi siempre, es el espacio con el criterio suficiente para presentar al uno al otro.', 'For emerging artists, the practical reading of this data is simple: the market is looking for what they produce. The problem isn\'t demand — it\'s visibility. The new buyer wants to discover. The new artist wants to be found. What\'s missing, almost always, is the space with enough judgement to introduce one to the other.'),
      ],
    },
    {
      slug: 'por-que-arte-no-pierde-valor',
      date: L('20 may 2026', 'May 20, 2026'),
      title: L('Por qué el arte sobrevive a las crisis económicas mejor que casi cualquier otro activo', 'Why art survives economic crises better than almost any other asset'),
      excerpt: L('En 2008, el mercado financiero colapsó. El arte también cayó, pero se recuperó más rápido. Hay una razón histórica para eso.', 'In 2008, the financial market collapsed. Art fell too, but recovered faster. There\'s a historical reason for that.'),
      image: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1200&q=80&fit=crop',
      imageAlt: L('Pintura abstracta en gran formato sobre pared de galería', 'Large-format abstract painting on a gallery wall'),
      imageCaption: L('Arte abstracto contemporáneo · Foto: Unsplash (uso libre)', 'Contemporary abstract art · Photo: Unsplash (free use)'),
      body: [
        L('Cuando los mercados financieros entran en pánico, el capital busca refugios. El oro es el más conocido. El arte es el menos obvio, pero tiene un historial más largo que casi cualquier instrumento financiero moderno.', 'When financial markets panic, capital looks for safe havens. Gold is the best known. Art is the least obvious, but it has a longer track record than almost any modern financial instrument.'),
        L('Durante la Gran Depresión de los años 30, las colecciones de arte de grandes familias estadounidenses se mantuvieron. En algunos casos, obras que se creían invendibles encontraron compradores europeos que querían sacar capital de un continente al borde de la guerra. El arte cruzó fronteras cuando el dinero no podía.', 'During the Great Depression of the 1930s, the art collections of major American families held up. In some cases, works thought unsellable found European buyers who wanted to move capital out of a continent on the brink of war. Art crossed borders when money couldn\'t.'),
        L('En 2008, el mercado del arte cayó junto con todo lo demás. Pero la caída fue más moderada y la recuperación fue más rápida. Entre 2009 y 2014, el índice de precios del arte contemporáneo subió más del 70%, superando en ese período a la bolsa de valores de casi cualquier mercado desarrollado.', 'In 2008, the art market fell along with everything else. But the drop was more moderate and the recovery faster. Between 2009 and 2014, the contemporary art price index rose more than 70%, outperforming in that period the stock market of almost any developed economy.'),
        L('La razón estructural es simple: el arte es escaso por definición. Una obra específica de un artista específico no puede reproducirse en cantidad. Cuando muere un artista, su catálogo queda fijo para siempre. El mercado puede subir o bajar, pero la cantidad de Modiglianis disponibles no cambia. Esa escasez estructural funciona como piso.', 'The structural reason is simple: art is scarce by definition. A specific work by a specific artist cannot be reproduced in quantity. When an artist dies, their catalogue is fixed forever. The market may rise or fall, but the number of available Modiglianis doesn\'t change. That structural scarcity acts as a floor.'),
        L('El caso de El Greco ilustra el punto mejor que ningún otro. Durante casi dos siglos después de su muerte en 1614, sus obras estaban devaluadas: el estilo considerado "extravagante" y "distorsionado" no encajaba con el gusto académico europeo. Se vendían barato. En el siglo XIX, los impresionistas españoles y luego Cézanne "redescubrieron" su trabajo y el mercado lo recalibró completamente. Los que compraron El Greco barato en el siglo XVIII hicieron una de las mejores inversiones de la historia sin saberlo.', 'The case of El Greco illustrates the point better than any other. For nearly two centuries after his death in 1614, his works were devalued: the style, considered "extravagant" and "distorted", didn\'t fit European academic taste. They sold cheap. In the 19th century, Spanish impressionists and then Cézanne "rediscovered" his work and the market completely recalibrated. Those who bought cheap El Grecos in the 18th century made one of the best investments in history without knowing it.'),
        L('Van Gogh es el caso extremo: murió casi sin vender nada. Hoy es el artista con más obras en el top 50 de ventas en subasta de la historia. El tiempo fue el único factor que cambió.', 'Van Gogh is the extreme case: he died having sold almost nothing. Today he is the artist with the most works in the all-time top 50 auction sales. Time was the only factor that changed.'),
        L('Nada de esto significa que comprar arte sea una inversión financiera simple o predecible. La mayoría de las obras compradas hoy no valdrán más en veinte años. Pero las que sí — las que tienen detrás un artista genuino, una obra coherente y un momento de descubrimiento documentado — tienden a comportarse como el oro: como reserva de valor que sobrevive a las tormentas.', 'None of this means buying art is a simple or predictable financial investment. Most works bought today won\'t be worth more in twenty years. But the ones that are — those backed by a genuine artist, a coherent body of work and a documented moment of discovery — tend to behave like gold: a store of value that survives the storms.'),
        L('El coleccionista inteligente no compra para vender. Compra porque la obra le importa, y eso, paradójicamente, es lo que más le protege: si el mercado cae, todavía tiene algo en la pared que vale la pena mirar.', 'The smart collector doesn\'t buy to sell. They buy because the work matters to them, and that, paradoxically, is what protects them most: if the market falls, they still have something on the wall worth looking at.'),
      ],
    },
    {
      slug: 'color-historia-pigmentos',
      date: L('10 may 2026', 'May 10, 2026'),
      title: L('La historia violenta y fascinante del color: cómo los artistas consiguieron sus pigmentos', 'The violent, fascinating history of color: how artists got their pigments'),
      excerpt: L('El azul ultramarino valía más que el oro. El verde esmeralda era venenoso. El blanco de plomo mataba a quien lo usaba. Pintar siempre tuvo un costo.', 'Ultramarine blue was worth more than gold. Emerald green was poisonous. Lead white killed those who used it. Painting always had a cost.'),
      image: wiki('Mona Lisa, by Leonardo da Vinci, from C2RMF retouched.jpg', 900),
      imageAlt: L('La Gioconda de Leonardo da Vinci, circa 1503–1519, Museo del Louvre, París', 'The Mona Lisa by Leonardo da Vinci, circa 1503–1519, the Louvre, Paris'),
      imageCaption: L('La Gioconda · Leonardo da Vinci · circa 1503 · Louvre, París · Dominio público', 'Mona Lisa · Leonardo da Vinci · circa 1503 · Louvre, Paris · Public domain'),
      body: [
        L('Antes de que existiera el tubo de pintura, conseguir un color específico podía costar fortunas, años de viaje, o la vida. La historia del arte es también la historia de cómo los seres humanos persiguieron el color con una obsesión que hoy resulta difícil de imaginar.', 'Before the paint tube existed, obtaining a specific color could cost fortunes, years of travel, or a life. The history of art is also the history of how humans pursued color with an obsession that\'s hard to imagine today.'),
        L('El azul ultramarino — ese azul profundo que aparece en los mantos de la Virgen en casi toda la pintura medieval y renacentista — se fabricaba a partir del lapislázuli, una piedra semipreciosa que solo existía en una sola mina en el mundo: en las montañas de Badajshan, en lo que hoy es Afganistán. Había que extraerla, transportarla a través de Asia Central y Europa, y molerla durante semanas. Era más cara que el oro por peso. Los contratos de encargo de la época especificaban exactamente cuántos gramos de ultramarino podía usar el artista y en qué partes de la obra.', 'Ultramarine blue — that deep blue that appears in the Virgin\'s robes in almost all medieval and Renaissance painting — was made from lapis lazuli, a semiprecious stone that existed in only one mine in the world: in the mountains of Badakhshan, in what is now Afghanistan. It had to be mined, transported across Central Asia and Europe, and ground for weeks. It was more expensive than gold by weight. Commission contracts of the era specified exactly how many grams of ultramarine the artist could use and in which parts of the work.'),
        L('El verde esmeralda, popular en la pintura del siglo XIX, era una combinación de arsénico y cobre que producía un verde brillante sin precedente. También era altamente tóxico. Se cree que las habitaciones tapizadas con papel pintado de ese color — que se fabricaba con el mismo pigmento — contribuyeron a la mala salud de Napoleón en su exilio en Santa Elena. Algunos historiadores sospechan que el arsénico del papel de sus paredes fue un factor en su muerte.', 'Emerald green, popular in 19th-century painting, was a combination of arsenic and copper that produced an unprecedented bright green. It was also highly toxic. Rooms papered with wallpaper of that color — made with the same pigment — are believed to have contributed to Napoleon\'s poor health during his exile on Saint Helena. Some historians suspect the arsenic in his wallpaper was a factor in his death.'),
        L('El blanco de plomo fue el blanco estándar de la pintura europea desde la antigüedad hasta el siglo XX. Era brillante, opaco y secaba bien. También era lentamente letal. La exposición prolongada al plomo provoca daño neurológico acumulativo. Goya, que usó grandes cantidades en su técnica, desarrolló una sordera progresiva y un estado mental que algunos historiadores atribuyen parcialmente a la intoxicación crónica. Sus "Pinturas negras" — los murales que cubrió en su propia casa — fueron hechos con plomo.', 'Lead white was the standard white of European painting from antiquity to the 20th century. It was bright, opaque and dried well. It was also slowly lethal. Prolonged lead exposure causes cumulative neurological damage. Goya, who used large amounts in his technique, developed progressive deafness and a mental state that some historians partly attribute to chronic poisoning. His "Black Paintings" — the murals he covered the walls of his own house with — were made with lead.'),
        L('El amarillo de Nápoles, usado desde el Renacimiento, se fabricaba con antimoniato de plomo: también tóxico, también brillante, también difícil de reemplazar. El pigmento índigo — el azul más oscuro de la pintura asiática y europea — dependía de una planta tropical que se cultivaba principalmente con trabajo esclavo en las colonias. El comercio del arte y el comercio de personas estuvieron conectados por el color.', 'Naples yellow, used since the Renaissance, was made with lead antimonate: also toxic, also bright, also hard to replace. The indigo pigment — the darkest blue of Asian and European painting — depended on a tropical plant grown mostly with slave labor in the colonies. The art trade and the trade in people were connected by color.'),
        L('El primer color sintético de la historia moderna fue el azul de Prusia, descubierto por accidente en Berlín alrededor de 1704. Un fabricante de pinturas intentaba hacer rojo y obtuvo azul. Cambió el mercado del color para siempre: por primera vez, un tono específico podía producirse de forma consistente, barata y en cantidad. El impresionismo — con su obsesión por capturar la luz — no hubiera existido sin la revolución de los pigmentos sintéticos del siglo XIX.', 'The first synthetic color of modern history was Prussian blue, discovered by accident in Berlin around 1704. A paint maker was trying to make red and got blue. It changed the color market forever: for the first time, a specific shade could be produced consistently, cheaply and in quantity. Impressionism — with its obsession with capturing light — would not have existed without the 19th-century synthetic pigment revolution.'),
        L('Hoy, los tubos de óleo en cualquier ferretería de arte contienen colores que en el Renacimiento habrían costado el equivalente de meses de trabajo. El azul ultramarino artificial, sintetizado por primera vez en 1828, es indistinguible al ojo del original y cuesta céntimos. Lo que los artistas renacentistas negociaban por gramos, hoy se compra por kilos. Pero algo se perdió en esa democratización: el peso de saber que ese azul venía de un lugar específico en el mundo, transportado por manos específicas, valioso por su rareza absoluta.', 'Today, oil tubes in any art store contain colors that in the Renaissance would have cost the equivalent of months of work. Artificial ultramarine blue, first synthesized in 1828, is indistinguishable to the eye from the original and costs cents. What Renaissance artists negotiated by the gram is now bought by the kilo. But something was lost in that democratization: the weight of knowing that blue came from a specific place in the world, carried by specific hands, valuable for its absolute rarity.'),
      ],
    },
  ];
}

export function getArticleBySlug(slug, locale) {
  return getArticles(locale).find((a) => a.slug === slug);
}
